# Generated by Django 4.2.13 on 2024-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_address_city_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'LLC'), ('c_corp', 'C Corp'), ('s_corp', 'S Corp'), ('benefit_corporation', 'Benefit Corporation'), ('close_corporation', 'Close Corporation'), ('nonprofit_corporation', 'Nonprofit Corporation'), ('fl_profit_corp', 'Florida Profit Corp')], default='Florida Profit Corp', max_length=100),
        ),
    ]
