# Generated by Django 4.2.13 on 2024-05-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_ssn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'LLC'), ('c_corp', 'C Corp'), ('s_corp', 'S Corp'), ('benefit_corporation', 'Benefit Corporation'), ('close_corporation', 'Close Corporation'), ('nonprofit_corporation', 'Nonprofit Corporation'), ('fl_profit_corp', 'Florida Profit Corp')], default='fl_profit_corp', max_length=100),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.business')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.person')),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='earnings (USD)')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.business')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='businesses',
            field=models.ManyToManyField(through='payroll.Employment', to='payroll.business'),
        ),
    ]
