# Generated by Django 4.2.13 on 2024-05-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_person_last_ssn_alter_business_business_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='earnings',
            new_name='amount',
        ),
    ]
